version: '2'
services:
  db:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="${DB_ROOT_PASSWORD}"
      - MYSQL_DATABASE="${DB_DATABASE}"
      - MYSQL_USER="${DB_USER}"
      - MYSQL_PASSWORD="${DB_PASSWORD}"
      - MYSQL_PORT=3306
    volumes:
      - ./docker/datadir:/var/lib/mysql
      - ./docker/init-dump:/docker-entrypoint-initdb.d
    ports:
      - "${HOST_DB_PORT}:3306"

  memcached:
    image: memcached:alpine

  php:
    build: ./docker/image/php
    environment:
      - DB_HOST=db
      - DB_NAME="${DB_DATABASE}"
      - DB_USER="${DB_USER}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_PORT=3306
      - ENV_NAME=production
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    links:
      - db
      - memcached
    volumes:
      - .:/website
      - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/conf/php/conf.d/zzz_custom.ini:/usr/local/etc/php/conf.d/zzz_custom.ini:ro
    working_dir: /website

  web:
    image: nginx
    links:
      - php
    ports:
      - "${HOST_WEB_PORT}:80"
    volumes:
      - .:/website
      - ./docker/conf/nginx/conf.d:/etc/nginx/conf.d:ro
    working_dir: /website

